import 'package:flutter/material.dart';
import '../config/smart_dropdown_config.dart';
import '../config/smart_dropdown_pagination_config.dart';
import '../config/smart_dropdown_selection_config.dart';
import '../enums/selection_mode.dart';
import '../models/dropdown_item_state.dart';
import 'smart_search_dropdown.dart';

/// FormField wrapper for [SmartSearchDropdown] enabling Flutter [Form] validation and submission.
class SmartSearchDropdownFormField<T> extends FormField<dynamic> {
  SmartSearchDropdownFormField({
    super.key,
    List<T>? items,
    T? initialValue,
    List<T>? initialMultiValue,
    super.onSaved,
    super.validator,
    super.autovalidateMode,
    super.enabled = true,
    ValueChanged<T?>? onChanged,
    ValueChanged<List<T>>? onMultiChanged,
    String Function(T item)? itemLabelBuilder,
    String? Function(T item)? itemSubtitleBuilder,
    Widget? Function(T item)? itemIconBuilder,
    Widget? Function(T item)? itemAvatarBuilder,
    Widget? Function(T item)? itemStatusBuilder,
    Widget? Function(T item)? itemTrailingBuilder,
    Widget? Function(T item)? itemLeadingBuilder,
    bool Function(T item)? isItemDisabled,
    Object Function(T item)? itemIdExtractor,
    bool Function(T a, T b)? itemEquality,
    String Function(T item)? groupBy,
    Widget Function(BuildContext context, String groupName)? groupHeaderBuilder,
    Widget Function(BuildContext context, T item, SmartDropdownItemState state)?
        itemBuilder,
    Widget Function(BuildContext context, T item)? selectedItemBuilder,
    WidgetBuilder? emptyBuilder,
    Widget Function(BuildContext context, String error)? errorBuilder,
    WidgetBuilder? loadingBuilder,
    Future<T?> Function(String query)? onCreateOption,
    Widget Function(BuildContext context, ValueChanged<String> onChanged)?
        searchFieldBuilder,
    Widget Function(BuildContext context, T item, VoidCallback onRemove)?
        chipBuilder,
    bool? showSearch,
    bool? showClearButton,
    bool? showDropdownIcon,
    bool? showCheckbox,
    bool? showSelectAll,
    bool? showClearAll,
    bool? showRecent,
    bool? showPopular,
    bool? showStatus,
    bool? showScrollbar,
    bool? enablePagination,
    bool? enableGrouping,
    bool? enableCreateOption,
    bool? enableFilters,
    bool? enableAdaptive,
    Widget? dropdownIcon,
    Widget? expandedIcon,
    Widget? clearIcon,
    InputDecoration? decoration,
    bool readOnly = false,
    bool autofocus = false,
    FocusNode? focusNode,
    SmartDropdownConfig<T>? config,
    SmartDropdownSelectionConfig? selectionConfig,
    String hintText = 'Select Option',
    String? labelText,
    Widget? prefixIcon,
    Widget? trailingLabelWidget,
    String? searchHint,
    double? maxPanelHeight,
    bool Function(T item)? isItemEnabled,
    Future<List<T>> Function(String query)? asyncSearch,
    SmartDropdownPaginationConfig<T>? pagination,
    Future<DropdownPageResult<T>> Function(String query, int page)? loader,
    int? debounceMs,
    int? pageSize,
  }) : super(
          initialValue: (selectionConfig?.mode == SelectionMode.multiple)
              ? initialMultiValue
              : initialValue,
          builder: (FormFieldState<dynamic> state) {
            final isMulti = selectionConfig?.mode == SelectionMode.multiple;

            return SmartSearchDropdown<T>(
              items: items,
              value: !isMulti ? state.value as T? : null,
              selectedItems: isMulti ? (state.value as List<T>?) : null,
              onChanged: (val) {
                state.didChange(val);
                onChanged?.call(val);
              },
              onMultiChanged: (vals) {
                state.didChange(vals);
                onMultiChanged?.call(vals);
              },
              itemLabelBuilder: itemLabelBuilder,
              itemSubtitleBuilder: itemSubtitleBuilder,
              itemIconBuilder: itemIconBuilder,
              itemAvatarBuilder: itemAvatarBuilder,
              itemStatusBuilder: itemStatusBuilder,
              itemTrailingBuilder: itemTrailingBuilder,
              itemLeadingBuilder: itemLeadingBuilder,
              isItemDisabled: isItemDisabled,
              itemIdExtractor: itemIdExtractor,
              itemEquality: itemEquality,
              groupBy: groupBy,
              groupHeaderBuilder: groupHeaderBuilder,
              itemBuilder: itemBuilder,
              selectedItemBuilder: selectedItemBuilder,
              emptyBuilder: emptyBuilder,
              errorBuilder: errorBuilder,
              loadingBuilder: loadingBuilder,
              onCreateOption: onCreateOption,
              searchFieldBuilder: searchFieldBuilder,
              chipBuilder: chipBuilder,
              showSearch: showSearch,
              showClearButton: showClearButton,
              showDropdownIcon: showDropdownIcon,
              showCheckbox: showCheckbox,
              showSelectAll: showSelectAll,
              showClearAll: showClearAll,
              showRecent: showRecent,
              showPopular: showPopular,
              showStatus: showStatus,
              showScrollbar: showScrollbar,
              enablePagination: enablePagination,
              enableGrouping: enableGrouping,
              enableCreateOption: enableCreateOption,
              enableFilters: enableFilters,
              enableAdaptive: enableAdaptive,
              dropdownIcon: dropdownIcon,
              expandedIcon: expandedIcon,
              clearIcon: clearIcon,
              decoration: decoration,
              readOnly: readOnly,
              autofocus: autofocus,
              focusNode: focusNode,
              config: config,
              selection: selectionConfig,
              hintText: hintText,
              enabled: state.widget.enabled,
              errorText: state.errorText,
              labelText: labelText,
              prefixIcon: prefixIcon,
              trailingLabelWidget: trailingLabelWidget,
              searchHint: searchHint,
              maxPanelHeight: maxPanelHeight,
              isItemEnabled: isItemEnabled,
              asyncSearch: asyncSearch,
              pagination: pagination,
              loader: loader,
              debounceMs: debounceMs,
              pageSize: pageSize,
            );
          },
        );
}
